Add OLM prometheus exporter-operator to v0.2.2
3scale/3scaleops-olm-catalog pull request #2
Opened 2020-11-20 17:48 UTC by slopezz

Updates prometheus-exporter-operator to `v0.2.2`

Initially I created CSV/RELEASE version `v0.2.2-1`, which updated the available CSV correctly on every cluster, but by error, it didnit include the `replaces` field in the spec, so it didn't perform any update on installed operators with previews version `v0.2.1`.

It could be fixed by just fixing the already existing CSV `v0.2.2-1`, and using a new `RELEASE` env var, with a different content like `v0.2.2-2` (but it would be CSV `v0.2.2-1` and RELEASE `v0.2.2-2`). However, in order to follow current convention of CSV with its own RELEASE version, I prefered to create a new CSV/RELEASE `v0.2.2-2`, whose CSV includes  `replaces: prometheus-exporter-operator-threescale.v0.2.1-1` (so, replaces the original version `v0.2.1`).

2020-11-20 19:28 UTC, raelga approved these changes

2020-11-23 08:17 UTC, roivaz requested changes
The names of the csv files are wrong `olm-catalog/prometheus-exporter-operator/0.2.2-1/prometheus-exporter-operator-threescale.v0.2.1-1.clusterserviceversion.yaml` and `olm-catalog/prometheus-exporter-operator/0.2.2-2/prometheus-exporter-operator-threescale.v0.2.1-1.clusterserviceversion.yaml`, I don't think it matters for the olm releases, but we should at least correct them in the repo.

2020-11-23 09:32 UTC, slopezz commented
> The names of the csv files are wrong `olm-catalog/prometheus-exporter-operator/0.2.2-1/prometheus-exporter-operator-threescale.v0.2.1-1.clusterserviceversion.yaml` and `olm-catalog/prometheus-exporter-operator/0.2.2-2/prometheus-exporter-operator-threescale.v0.2.1-1.clusterserviceversion.yaml`, I don't think it matters for the olm releases, but we should at least correct them in the repo.

Nice catch!

Fixed on https://github.com/3scale/3scaleops-olm-catalog/pull/2/commits/7ffa64618103e772acddbd83ac112af846e0c5c4

2020-11-23 10:06 UTC, roivaz approved these changes

2020-11-23 10:07 UTC, merged